### PR TITLE
If postIds, friendIds etc are int[] we can't call ->remove() on the array

### PR DESCRIPTION
**Pull request by harikt**
Hi, 

I have been looking into the code, and it looks to me, if this is an array of int, then the call on `unfriend` will not work.

Correct me if I am wrong.

> NB : Nice mapper, so far I like it.

### CODE REVIEW

**Comment by TimeToogo** [comment]
Hi Harikt,

Thank you for your pull request. I can see why these docblocks are misleading, in fact they are technically incorrect, these properties can only be instances of `EntityIdCollection`. This class implements `ArrayAccess` so the original code should be correct. However we add `|int[]` so PHPStorm can infer the correct type of the elements when `foreach`-ing the collection. If you know a better way to document the element type of a custom collection class please let us know and we will amend these docblocks as this is used quite extensively.

Thanks

**Comment by harikt** [comment]
Thank you for your explanation.

And this is an awesome piece of work. :clap: . I tried with laravel and I am very impressed with it.

**Comment by TimeToogo** [comment]
Thanks for the feedback!

In case you haven't found it yet [here is the initial documentation](http://dms-docs.readthedocs.io/en/latest/).

**Comment by harikt** [comment]
@TimeToogo yes I noticed that today, ie how I tried it.

> UPDATE : Here is my tweet https://twitter.com/harikt/status/887540361991671809 about the same.

**Pull request closed without merging**
