### PR TITLE
update code to support php 7.2

### PR DESCRIPTION
**Pull request by harikt**
* Added php 7.2 to .travis.yml .
* Fixed code failing on php 7.2

### CODE REVIEW

**Comment by TimeToogo** [comment]
Thanks for your contribution!

**Comment by harikt** [comment]
you are welcome :) . Thank you for merging the same.

Any thoughts on https://github.com/dms-org/core/pull/3 ?

**Comment by harikt** [comment]
Can you make a release for this change so that the travis will no longer report the errors on the dependencies repos ?

It will be very helpful.

**Comment by TimeToogo** [comment]
Just tagged 0.8.3 :)

**Pull request merged**
